teams:
  - name: lf-staff
    maintainers:
      - jwagantall
      - ryjones
    members:
      - SeanBohan
      - thelinuxfoundation
  - name: lineth-admin
    maintainers:
      - julien-marchand
  - name: lineth-maintain
    maintainers:
      - julien-marchand
    members:
      - eloi010
  - name: lineth-write
    maintainers:
      - julien-marchand
    members:
      - daniellehrner
      - eloi010
      - FlorianHuc
      - fab-10
    formation:
      - team-coordinator
      - team-contracts
      - team-prover-wizard
      - team-prover-recursion
      - team-prover-perf
      - team-arithmetization
  - name: team-coordinator
    maintainers:
      - fluentcrafter
    members:
      - Filter94
      - gauravahuja
      - jonesho
      - nadeemb53
  - name: team-contracts
    maintainers:
      - thedarkjester
    members:
      - alainncls
      - kyzooghost
      - Othryades
      - pajicf
      - VGau
  - name: team-engineering
    maintainers:
      - julien-marchand
    formation:
      - team-coordinator
      - team-contracts
  - name: team-prover-wizard
    maintainers:
      - AlexandreBelling
    members:
      - bogdanbear
      - Soleimani193
      - ThomasPiellard
  - name: team-prover-recursion
    maintainers:
      - ivokub
    members:
      - arijitdutta67
      - Tabaie
      - YaoJGalteland
  - name: team-prover-perf
    maintainers:
      - gbotrel
    members:
      - gusiri
      - srinathln7
      - yelhousni
  - name: team-prover
    maintainers:
      - AlexandreBelling
    formation:
      - team-prover-wizard
      - team-prover-recursion
      - team-prover-perf
      - team-gnark
  - name: team-arithmetization
    maintainers:
      - OlivierBBB
    members:
      - amkCha
      - DavePearce
      - letypequividelespoubelles
      - lorenzogentile404
  - name: lineth-triage
    maintainers:
      - julien-marchand
  - name: zkc-admin
    maintainers:
      - DavePearce
repositories:
  - name: .github
    teams:
      lf-staff: maintain
      lineth-admin: maintain
      lineth-maintain: write
    visibility: public
  - name: governance
    teams:
      lf-staff: maintain
      lineth-admin: maintain
      lineth-maintain: write
    visibility: public
  - name: zkc
    teams:
      lineth-admin: admin
      zkc-admin: admin
      lineth-maintain: maintain
      lineth-write: write
      lineth-triage: triage
    visibility: public
  - name: lineth-monorepo
    teams:
      lineth-admin: admin
      lineth-maintain: maintain
      lineth-write: write
      lineth-triage: triage
    visibility: public
